### PR TITLE
Responses updated

### PR DESCRIPTION
**Pull request by andreafspeziale**
Hi,
I've actually tested for my lib a lot of APIs and write a lot of examples and documentation for it, so I've updated the official docu too.

- Blocks section
- Account section
- Multisig section
- Signature section
- Delegate section

### CODE REVIEW

**Comment by karmacoma** [comment]
Thank you @andreafspeziale 👍

**Comment by Isabello** [comment]
Looks Great, thanks @andreafspeziale

**Comment by andreafspeziale** [comment]
You are welcome @Isabello @karmacoma. Hope you don't mind if I'll add more fix in the next days (:
I don't want be annoying.

Cheers

**Comment by 4miners** [comment]
@andreafspeziale You're welcome to do that, your work is appreciated.

**Pull request merged**
